CREATE TABLE AUTOMOBILE (
    ID                 BIGINT identity(1,1) NOT NULL,
    BROJOGLASA         BIGINT NOT NULL,
    NASLOV             VARCHAR(100),
    CENA               FLOAT,
    URL                VARCHAR(8000),
    VOZILO             VARCHAR(50),
    MARKA              VARCHAR(20),
    MODEL              VARCHAR(20),
    GODINAPROIZVODNJE  INTEGER,
    KAROSERIJA         VARCHAR(50),
    GORIVO             VARCHAR(50),
    FIKSNACENA         SMALLINT,
    ZAMENA             SMALLINT,
    DATUMPOSTAVLJANJA  DATE,
    KUBIKAZA           INTEGER,
    SNAGA_KW           INTEGER,
    SNAGA_KS           INTEGER,
    KILOMETRAZA        INTEGER,
    EMISIONAKLASA      VARCHAR(30),
    POGON              VARCHAR(30),
    MENJAC             VARCHAR(30),
    BROJVRATA          VARCHAR(10),
    BROJSEDISTA        VARCHAR(10),
    STRANAVOLANA       VARCHAR(20),
    KLIMA              VARCHAR(30),
    BOJA               VARCHAR(20),
    REGISTROVANDO      VARCHAR(20),
    POREKLOVOZILA      VARCHAR(50),
    OPIS               VARCHAR(4000),
    KONTAKT            VARCHAR(2000),
    THREAD             VARCHAR(20),
    DATUM_DODAVANJA    datetime,
    DATUM_AZURIRANJA   datetime,
	constraint PK_Automobile primary key nonclustered (id) 
);