/******************************************************************************/
/***                Generated by IBExpert 12.4.2014 23:22:23                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_AUTOMOBIL_ID;

CREATE TABLE AUTOMOBIL (
    ID                 BIGINT NOT NULL,
    BROJOGLASA         BIGINT NOT NULL,
    NASLOV             VARCHAR(100),
    CENA               FLOAT,
    URL                VARCHAR(8190),
    VOZILO             VARCHAR(50),
    MARKA              VARCHAR(20),
    MODEL              VARCHAR(20),
    GODINAPROIZVODNJE  INTEGER,
    KAROSERIJA         VARCHAR(50),
    GORIVO             VARCHAR(50),
    FIKSNACENA         SMALLINT,
    ZAMENA             SMALLINT,
    DATUMPOSTAVLJANJA  DATE,
    KUBIKAZA           INTEGER,
    SNAGA_KW           INTEGER,
    SNAGA_KS           INTEGER,
    KILOMETRAZA        INTEGER,
    EMISIONAKLASA      VARCHAR(30),
    POGON              VARCHAR(30),
    MENJAC             VARCHAR(30),
    BROJVRATA          VARCHAR(10),
    BROJSEDISTA        VARCHAR(10),
    STRANAVOLANA       VARCHAR(20),
    KLIMA              VARCHAR(30),
    BOJA               VARCHAR(20),
    REGISTROVANDO      VARCHAR(20),
    POREKLOVOZILA      VARCHAR(50),
    OPIS               VARCHAR(4000),
    KONTAKT            VARCHAR(2000),
    THREAD             VARCHAR(20),
    DATUM_DODAVANJA    TIMESTAMP,
    DATUM_AZURIRANJA   TIMESTAMP
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE AUTOMOBIL ADD CONSTRAINT PK_AUTOMOBIL PRIMARY KEY (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX AUTOMOBIL_IDX1 ON AUTOMOBIL (BROJOGLASA);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: AUTOMOBIL_BI0 */
CREATE OR ALTER TRIGGER AUTOMOBIL_BI0 FOR AUTOMOBIL
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.id is null) then
    new.id =  GEN_ID(gen_automobil_id, 1);
end
^


/* Trigger: AUTOMOBIL_BI_DATUM */
CREATE OR ALTER TRIGGER AUTOMOBIL_BI_DATUM FOR AUTOMOBIL
ACTIVE BEFORE INSERT POSITION 1
as
begin
  new.datum_dodavanja = current_timestamp;
end
^


/* Trigger: AUTOMOBIL_BU_DATUM */
CREATE OR ALTER TRIGGER AUTOMOBIL_BU_DATUM FOR AUTOMOBIL
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
  new.datum_azuriranja = current_timestamp;
end
^


SET TERM ; ^



/******************************************************************************/
/***                          Fields descriptions                           ***/
/******************************************************************************/

COMMENT ON COLUMN AUTOMOBIL.VOZILO IS 
'Novo ili polovno.';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

